name:                IdiomSolitaire
version:             0.1.0.0
github:              "githubuser/IdiomSolitaire"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/IdiomSolitaire#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- esqueleto
- persistent
- persistent-template
- persistent-sqlite
- microlens
- microlens-aeson
- containers
- unordered-containers
- cryptohash-sha256
- bytestring
- mtl
- text

library:
  source-dirs: src

executables:
  IdiomSolitaire-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IdiomSolitaire

tests:
  IdiomSolitaire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IdiomSolitaire
